'use client'

import { useState, useEffect } from 'react'
import { MaintenanceRecord } from '@/types/maintenance'

interface MaintenanceSummaryViewProps {
    record: MaintenanceRecord
    onClose: () => void
}

export default function MaintenanceSummaryView({ record, onClose }: MaintenanceSummaryViewProps) {
    const [copied, setCopied] = useState(false)

    const formatDate = (dateString: string) => {
        const date = new Date(dateString)
        const day = String(date.getDate()).padStart(2, '0')
        const month = String(date.getMonth() + 1).padStart(2, '0')
        const year = date.getFullYear()
        return `${day}/${month}/${year}`
    }

    const formatTime = (timeString: string) => {
        if (!timeString) return ''
        return timeString.substring(0, 5)
    }

    const getWhatsAppSummary = () => {
        const checklistText = record.checklist && record.checklist.length > 0
            ? record.checklist.map(item => `- ${item.label}: ${item.status === 'not-tested' ? 'N/A' : item.status.toUpperCase()}`).join('\n')
            : 'No checklist data'

        return `*Maintenance Summary - ${record.maintenance_number}*
------------------------------
*Server:* ${record.server_name}
*Client:* ${record.client_name}
*Schedule:* ${formatDate(record.maintenance_date)} (${formatTime(record.start_time)} - ${formatTime(record.end_time)})
*Reason:* ${record.maintenance_reason}
*Team:* ${record.performed_by} (Approved by: ${record.approver})
*Status:* ${record.status.toUpperCase()}

*Checklist:*
${checklistText}
------------------------------
Generated by Nautilus SIP Pte Ltd.`
    }

    // Handle ESC key to close
    useEffect(() => {
        const handleEsc = (e: KeyboardEvent) => {
            if (e.key === 'Escape') onClose()
        }
        window.addEventListener('keydown', handleEsc)
        return () => window.removeEventListener('keydown', handleEsc)
    }, [onClose])

    const copyToClipboard = () => {
        const text = getWhatsAppSummary()
        navigator.clipboard.writeText(text)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    return (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-md z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-3xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col border border-slate-200 animate-in fade-in zoom-in duration-150">
                {/* Header */}
                <div className="px-6 py-5 border-b border-slate-100 flex justify-between items-center bg-gradient-to-r from-slate-50 to-white">
                    <div>
                        <h2 className="text-xl font-black text-slate-800 tracking-tight leading-none">MAINTENANCE SUMMARY</h2>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-slate-100 rounded-xl text-slate-400 hover:text-slate-600 transition-all"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Content */}
                <div className="p-6 bg-slate-50/30 overflow-y-auto max-h-[60vh]">
                    <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm font-mono text-xs leading-relaxed text-slate-700 whitespace-pre-wrap">
                        {getWhatsAppSummary()}
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 bg-white border-t border-slate-100 flex gap-3">
                    <button
                        onClick={copyToClipboard}
                        className={`flex-1 flex items-center justify-center gap-2 py-3 rounded-2xl text-sm font-black transition-all transform active:scale-95 ${copied
                            ? 'bg-green-500 text-white shadow-lg shadow-green-200'
                            : 'bg-[#25D366] text-white hover:bg-[#128C7E] shadow-lg shadow-green-100'
                            }`}
                    >
                        {copied ? (
                            <>
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="3" d="M5 13l4 4L19 7" />
                                </svg>
                                COPIED TO CLIPBOARD
                            </>
                        ) : (
                            <>
                                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                                </svg>
                                COPY FOR WHATSAPP
                            </>
                        )}
                    </button>
                    <button
                        onClick={onClose}
                        className="px-8 py-3 bg-slate-100 text-slate-600 rounded-2xl text-sm font-black uppercase tracking-widest hover:bg-slate-200 transition-colors transform active:scale-95"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    )
}
