'use client'

import { useEffect } from 'react'
import { MaintenanceRecord } from '@/types/maintenance'

interface MaintenanceSummaryViewProps {
    record: MaintenanceRecord
    onClose: () => void
}

export default function MaintenanceSummaryView({ record, onClose }: MaintenanceSummaryViewProps) {
    const formatDate = (dateString: string) => {
        const date = new Date(dateString)
        const day = String(date.getDate()).padStart(2, '0')
        const month = String(date.getMonth() + 1).padStart(2, '0')
        const year = date.getFullYear()
        return `${day}/${month}/${year}`
    }

    const formatTime = (timeString: string) => {
        if (!timeString) return ''
        return timeString.substring(0, 5)
    }

    const getWhatsAppSummary = () => {
        const checklistText = record.checklist && record.checklist.length > 0
            ? record.checklist.map(item => `- ${item.label}: ${item.status === 'not-tested' ? 'N/A' : item.status.toUpperCase()}`).join('\n')
            : 'No checklist data'

        return `*Maintenance Summary - ${record.maintenance_number}*
------------------------------
*Server:* ${record.server_name}
*Client:* ${record.client_name}
*Schedule:* ${formatDate(record.maintenance_date)} (${formatTime(record.start_time)} - ${formatTime(record.end_time)})
*Reason:* ${record.maintenance_reason}
*Team:* ${record.performed_by} (Approved by: ${record.approver})
*Status:* ${record.status.toUpperCase()}

*Checklist:*
${checklistText}
------------------------------
Generated by Nautilus SIP Pte Ltd.`
    }

    // Handle ESC key to close
    useEffect(() => {
        const handleEsc = (e: KeyboardEvent) => {
            if (e.key === 'Escape') onClose()
        }
        window.addEventListener('keydown', handleEsc)
        return () => window.removeEventListener('keydown', handleEsc)
    }, [onClose])

    return (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-md z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-3xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col border border-slate-200 animate-in fade-in zoom-in duration-150">
                {/* Header */}
                <div className="px-6 py-5 border-b border-slate-100 flex justify-between items-center bg-gradient-to-r from-slate-50 to-white">
                    <div>
                        <h2 className="text-xl font-black text-slate-800 tracking-tight leading-none">MAINTENANCE SUMMARY</h2>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-slate-100 rounded-xl text-slate-400 hover:text-slate-600 transition-all"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Content */}
                <div className="p-6 bg-slate-50/30 overflow-y-auto max-h-[60vh]">
                    <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm font-mono text-xs leading-relaxed text-slate-700 whitespace-pre-wrap">
                        {getWhatsAppSummary()}
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 bg-white border-t border-slate-100 flex justify-end">
                    <button
                        onClick={onClose}
                        className="px-8 py-3 bg-slate-100 text-slate-600 rounded-2xl text-sm font-black uppercase tracking-widest hover:bg-slate-200 transition-colors transform active:scale-95"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    )
}
