'use client'

import { useEffect } from 'react'
import { MasterlistRecord } from '@/types/masterlist'

interface MasterlistViewProps {
    record: MasterlistRecord
    onClose: () => void
}

export default function MasterlistView({ record, onClose }: MasterlistViewProps) {
    const getSummaryContent = () => {
        return `*Customer Summary - ${record.company_name}*
------------------------------
*SIP # (Server ID):* ${record.sip_id || 'N/A'}
*Client Name:* ${record.company_name}
*Provider:* ${record.provider || 'N/A'}
*Category:* ${record.category || 'Standard'}
*Server URL:* ${record.server_url || 'N/A'}
*IP Address:* ${record.ip_address || 'N/A'}
*Subscription:* ${record.subscription_plan || 'N/A'}
*Endpoint:* ${record.endpoint_classification || 'N/A'}
*Trunks / Lines:* ${record.trunks_lines}
*Extensions:* ${record.extensions}
*Office Hours:* ${record.office_hours || 'N/A'}
*Client PIC:* ${record.client_contact || 'N/A'}
*Client Contact:* ${record.client_address || 'N/A'}
*Custom Features:* ${record.custom_features || 'None'}
*Internal Remarks:* ${record.remarks || 'None'}
------------------------------
Generated by Nautilus SIP Pte Ltd.`
    }

    // Handle ESC key to close
    useEffect(() => {
        const handleEsc = (e: KeyboardEvent) => {
            if (e.key === 'Escape') onClose()
        }
        window.addEventListener('keydown', handleEsc)
        return () => window.removeEventListener('keydown', handleEsc)
    }, [onClose])

    return (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-md z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-3xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col border border-slate-200 animate-in fade-in zoom-in duration-150">
                {/* Header */}
                <div className="px-6 py-5 border-b border-slate-100 flex justify-between items-center bg-gradient-to-r from-slate-50 to-white">
                    <div>
                        <h2 className="text-xl font-black text-slate-800 tracking-tight leading-none uppercase">Customer Summary</h2>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-slate-100 rounded-xl text-slate-400 hover:text-slate-600 transition-all"
                    >
                        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                {/* Content */}
                <div className="p-6 bg-slate-50/30 overflow-y-auto max-h-[60vh]">
                    <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm font-mono text-xs leading-relaxed text-slate-700 whitespace-pre-wrap">
                        {getSummaryContent()}
                    </div>
                </div>

                {/* Footer */}
                <div className="p-6 bg-white border-t border-slate-100 flex justify-end">
                    <button
                        onClick={onClose}
                        className="px-8 py-3 bg-slate-100 text-slate-600 rounded-2xl text-sm font-black uppercase tracking-widest hover:bg-slate-300 transition-colors transform active:scale-95"
                    >
                        Close
                    </button>
                </div>
            </div>
        </div>
    )
}
